apiVersion: batch/v1
kind: Job
metadata:
  name: coboljob
  labels:
    app: coboljob
spec:
  parallelism: 4    
  completions: 1    
  activeDeadlineSeconds: 1800 
  backoffLimit: 6
  template:
    spec:
      containers:
      - name: cobolubi
        image: quay.io/marcf5/cobolubi
        imagePullPolicy: Always
        command:
        - /bin/bash
        args:
          - -c
          - |
            cobc -x -free shortest.cbl
            export LD_LIBRARY_PATH=/usr/local/lib; ./shortest
      restartPolicy: Never
      imagePullSecrets:
        - name: staging-secret
